### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [huzongyao/AndLibNsgif#2]
What's the license of using this ?

**Comment by huzongyao** [comment]
Libnsgif is licensed under the MIT Licence.

**Comment by AndroidDeveloperLB** [comment]
Can you please update the main page of the repository and/or add a license file?

**Comment by huzongyao** [comment]
add in readme.md already

**Comment by AndroidDeveloperLB** [comment]
Oh sorry. I didn't notice it was there.
I was sure I searched for it.

**Comment by AndroidDeveloperLB** [comment]
Wait you added this recently ...
